/**
 * Root layout build-time options.
 *
 * The Looking Glass WebUI is shipped as a static SvelteKit bundle
 * (adapter-static) that is then embedded in the Go server binary
 * and served alongside an injected runtime env (`/_app/env.js`).
 * Because the env is generated by the backend at request time, any
 * prerendered HTML would carry a stale snapshot of the
 * configuration; we therefore opt out of prerendering and of
 * server-side rendering entirely, producing a pure client-rendered
 * SPA whose first paint waits for the runtime env to load.
 */

/** Disable build-time prerendering of every route under this layout. */
export const prerender = false;

/** Disable server-side rendering — render fully on the client. */
export const ssr = false;
