name: Release

on:
  release:
    types: [released]

permissions:
    contents: write
    packages: write

jobs:
  package-release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
      with:
        version: 9
    - uses: actions/setup-node@v7
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: webui/pnpm-lock.yaml
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: latest
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Protobuf
      run: |
        cd protobuf
        buf generate
    - name: Build Svelte WebUI
      run: |
        cd webui
        pnpm install --frozen-lockfile
        pnpm run build

    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/server"
        binary_name: "looking-glass"
        extra_files: LICENSE example.config.yaml
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/cli"
        binary_name: "lg-cli"
        extra_files: LICENSE

  docker-release:
    name: Release Docker Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
      with:
        platforms: arm64
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v4
      with:
        platforms: linux/amd64,linux/arm64
    - name: Log in to the Container registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: ghcr.io/as203038/looking-glass
    - name: Build and Push
      uses: docker/build-push-action@v7
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        sbom: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VERSION=${{ github.event.release.tag_name }}
